name: Check Owner Key in YML Files

on:
 pull_request:
    paths:
      - '**.yml'

jobs:
 check-owner-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Owner Key
        run: |
          echo "Checking for Owner Key in .yml files..."
          for file in $(find . -name "*.yml"); do
            if ! grep -q "Owner:" "$file"; then
              echo "Error: Owner key not found in $file"
              exit 1
            fi
          done
